title: <p align="center"> Fong Bao Xian </p>

logo: "/images/profile_pic/jpg?raw=true"

description: >
  <p align="center">
  <a href="https://www.linkedin.com/in/fong-bao-xian">LinkedIn</a> |
  <a href="https://https://github.com/fongbx">GitHub</a>
  </p>
  
  <p align="center">
  Data analyst, hobby coder and problem solver.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
